/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ubtechinc_cruzr_jnilearn_JNIDataLearn */

#ifndef _Included_com_ubtechinc_cruzr_jnilearn_JNIDataLearn
#define _Included_com_ubtechinc_cruzr_jnilearn_JNIDataLearn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getInt
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getLong
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getDouble
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getChar
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getByte
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getBoolean
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getShort
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setFloat
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setFloat
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setDouble
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setByte
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setByte
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setBoolean
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setShort
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setShort
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setStringArray
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setStringArray
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getStringArray
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getStringArray
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setIntArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setIntArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getIntArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getIntArray
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    setLongArray
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_setLongArray
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getLongArray
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getLongArray
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getString2DArray
 * Signature: ()[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getString2DArray
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getPersonArray
 * Signature: ()[Lcom/ubtechinc/cruzr/jnilearn/entity/Person;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getPersonArray
  (JNIEnv *, jobject);

/*
 * Class:     com_ubtechinc_cruzr_jnilearn_JNIDataLearn
 * Method:    getPerson
 * Signature: ()Lcom/ubtechinc/cruzr/jnilearn/entity/Person;
 */
JNIEXPORT jobject JNICALL Java_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_getPerson
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
