/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ubtechinc_cruzr_jnilearn_JNIDataLearn_InstanceHolder */

#ifndef _Included_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_InstanceHolder
#define _Included_com_ubtechinc_cruzr_jnilearn_JNIDataLearn_InstanceHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
