/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chihun_learn_jnidemo_JNIExceptionLearn */

#ifndef _Included_com_chihun_learn_jnidemo_JNIExceptionLearn
#define _Included_com_chihun_learn_jnidemo_JNIExceptionLearn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chihun_learn_jnidemo_JNIExceptionLearn
 * Method:    action
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_chihun_learn_jnidemo_JNIExceptionLearn_action
  (JNIEnv *, jclass, jstring);


JNIEXPORT jint JNICALL Java_com_chihun_learn_jnidemo_JNIExceptionLearn_jniDivide
     (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
